### ISSUE TITLE
Cannot run piston-example on Fedora24 virtual machine

### ISSUE THREAD

**Issue by behtgod** [PistonDevelopers/piston-examples#360]
Hello,
I got the error when `cargo run`
> Running \`target/debug/hello_world\`
>     thread \'<main>\' panicked at 'called \`Result::unwrap()\` on an \`Err\` value:        DescriptorInit(PixelExport(0, None))', ../src/libcore/result.rs:785
>     stack backtrace:
>        1:     0x55ac254c318f - std::sys::backtrace::tracing:: imp::write::h3800f45f421043b8
>        2:     0x55ac254c60fb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
>        3:     0x55ac254c5d83 - std::panicking::default_hook::hf3839060ccbb8764
>        4:     0x55ac254bb1fd - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
>        5:     0x55ac254c6341 - std::panicking::begin_panic::h9bf160aee246b9f6
>        6:     0x55ac254bc18a - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
>        7:     0x55ac254c62de - rust_begin_unwind
>        8:     0x55ac254fb9cf - core::panicking::panic_fmt::h93df64e7370b5253
>        9:     0x55ac2529eeb8 - core::result::unwrap_failed::h34f755f6048b6de0
>                         at ../src/libcore/macros.rs:29
>       10:     0x55ac2529ec69 - _<std..result..Result<T, E>>::unwrap::h96438632a78f8df6
>                         at ../src/libcore/result.rs:723
>       11:     0x55ac2529eaf2 - _<gfx_graphics..back_end..Gfx2d<R>>:: new::_$u7b$$u7b$closure$u7d$$u7d$::h892aa87452081017
>       12:     0x55ac2529f683 - _<gfx_graphics..back_end..PsoStencil<T>>:: new::h5b90be7427b9a44c
>                         at /home/behtgod/.cargo/registry/src/github.com-1ecc6299db9ec823/piston2d-gfx_graphics-0.30.0/src/back_end.rs:123
>       13:     0x55ac2528fc8d - _<gfx_graphics..back_end..Gfx2d<R>>:: new::h93749121f0ff7f70
>                         at /home/behtgod/.cargo/registry/src/github.com-1ecc6299db9ec823/piston2d-gfx_graphics-0.30.0/src/back_end.rs:230
>       14:     0x55ac2527e6f5 - _<piston_window..PistonWindow<W>>:: new::h9f08d84d4cfdc4f6
>                         at /home/behtgod/.cargo/registry/src/github.com-1ecc6299db9ec823/piston_window-0.50.0/src/lib.rs:188
>       15:     0x55ac2527de30 - _<piston_window..PistonWindow<W> as piston_window..BuildFromWindowSettings>::build_from_window_settings::h905443bc68b47be2
>                         at /home/behtgod/.cargo/registry/src/github.com-1ecc6299db9ec823/piston_window-0.50.0/src/lib.rs:146
>       16:     0x55ac2527daab - window::WindowSettings::build::h852f89105593d6ff
>                         at /home/behtgod/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.21.0/src/lib.rs:349
>       17:     0x55ac25272ddf - hello_world::main::h828adf8c4b210db6
>                         at src/hello_world.rs:7
>       18:     0x55ac254c59c8 - std::panicking::try::call::hbbf4746cba890ca7
>       19:     0x55ac254cfbdb - __rust_try
>       20:     0x55ac254cfb7e - __rust_maybe_catch_panic
>       21:     0x55ac254c546e - std::rt::lang_start::hbcefdc316c2fbd45
>       22:     0x55ac252eebc9 - main
>       23:     0x7f671f82b730 - __libc_start_main
>       24:     0x55ac25272bf8 - _start
>       25:                0x0 - <unknown>
>     error: Process didn't exit successfully: \`target/debug/hello_world\` (exit code: 101)

The OS is feroda24 virtual machine.

**Comment by mark-blum** [comment]
I am having this problem too, except on a non-virtual Arch Linux machine using rust 1.13. This affects all the examples except for cube.rs for some reason. It seems to me that the code is panicking during .build() of making the window (instead of returning an Err(...)), though in my case it seems to be because of make_current in glutin.

Here's my backtrace as well since it seems to be a bit different to the one above.

```
RUST_BACKTRACE=1 cargo run --bin hello_world              :(
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hello_world`
thread 'main' panicked at 'glx::MakeCurrent failed', /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/api/glx/mod.rs:112
stack backtrace:
   1:     0x563ac13052fa - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563ac1307f3f - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x563ac1307b3e - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x563ac13083e7 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x563ac11d7523 - std::panicking::begin_panic::h1dc990fced681ffe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x563ac11ec561 - <glutin::api::glx::Context as glutin::GlContext>::make_current::hba0d47ce0980442f
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/api/glx/mod.rs:112
   7:     0x563ac11178a7 - <glutin::platform::platform::x11::Window as glutin::GlContext>::make_current::he391e39cbddbea7c
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/platform/linux/x11.rs:224
   8:     0x563ac1117e95 - <glutin::platform::platform::api_dispatch::Window as glutin::GlContext>::make_current::h5fa21dfe0a0ad932
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/platform/linux/api_dispatch.rs:204
   9:     0x563ac111609b - glutin::window::<impl glutin::Window>::make_current::h2bd59c32b54a6569
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/window.rs:416
  10:     0x563ac1118c9e - glutin_window::GlutinWindow::new::h68d8bd8c48e6381a
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:101
  11:     0x563ac111b45b - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::he87a8a1fc851c86a
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:361
  12:     0x563ac10b4a8b - window::WindowSettings::build::hf611998bfa6c9929
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.24.0/src/lib.rs:367
  13:     0x563ac10c7dfb - <piston_window::PistonWindow<W> as window::BuildFromWindowSettings>::build_from_window_settings::hcbb82cacd43ebf31
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/piston_window-0.58.0/src/lib.rs:147
  14:     0x563ac10b4a4b - window::WindowSettings::build::h60961f9cc3ad0bb8
                        at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.24.0/src/lib.rs:367
  15:     0x563ac10d6868 - hello_world::main::h97715eb4a983057c
                        at /home/mark/rust/piston-examples/src/hello_world.rs:7
  16:     0x563ac130f27a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  17:     0x563ac1308b26 - std::rt::lang_start::h832f9067ed8c4dd4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  18:     0x563ac10d8842 - main
  19:     0x7fd1a6253290 - __libc_start_main
  20:     0x563ac102f149 - _start
  21:                0x0 - <unknown>

```
