### ISSUE TITLE
Examples crash on Windows 7 running in Parallel Desktop.

### ISSUE THREAD

**Issue by Jason5Lee** [PistonDevelopers/piston-examples#428]
The examples work on my Mac and my PC. but when I test them on Windows 7 running in Parallel Desktop, only `multi_window` works, others crash with the following message.

```
thread 'main' panicked at 'gl function was not loaded', <path>/gl_bindings.rs:1506:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The backtrace message of `hello_world` is

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound', src\libcore\result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: BaseThreadInitThunk
  16: RtlUserThreadStart
```
Toolchain: stable-x86_64-pc-windows-msvc
Compiling option: release

**Comment by Jason5Lee** [comment]
It appears that it is because Parallel Desktop only supports core profile. It can be solved by specified OpenGL version to 2.1.
