### ISSUE TITLE
Hello World (and all other examples) crash on Windows 10 x64 with Rust stable 1.48.0 - thread 'main' panicked at 'attempted to zero-initialize type ...

### ISSUE THREAD

**Issue by python50** [PistonDevelopers/piston-examples#464]
I am running Rust Stable 1.48 on the x64 version of Windows 10.

```
Jason@DESKTOP-8MI81SO MINGW64 /c/Users/Jason/Desktop/piston-examples (master)
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Jason\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.48.0 (7eac88abb 2020-11-16)
```

After building the examples trying to run hello_world results in the following crash.

```
Jason@DESKTOP-8MI81SO MINGW64 /c/Users/Jason/Desktop/piston-examples (master)
$ RUST_BACKTRACE=1 cargo run --bin hello_world
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target\debug\hello_world.exe`
"C:\\Users\\Jason\\Desktop\\piston-examples\\assets"
thread 'main' panicked at 'attempted to zero-initialize type `glutin::ContextWrapper<glutin::PossiblyCurrent, glutin::Window>`, which is invalid', C:\Users\Jason\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\mem\mod.rs:622:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:50
   3: core::mem::zeroed
             at C:\Users\Jason\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\mem\mod.rs:622
   4: glutin_window::{{impl}}::make_current
             at C:\Users\Jason\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.67.0\src\lib.rs:539
   5: piston_window::PistonWindow<glutin_window::GlutinWindow>::draw_2d<glutin_window::GlutinWindow,input::Event,closure-0,tuple<>>
             at C:\Users\Jason\.cargo\registry\src\github.com-1ecc6299db9ec823\piston_window-0.116.0\src\lib.rs:286
   6: hello_world::main
             at .\src\hello_world.rs:23
   7: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\Jason\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\hello_world.exe` (exit code: 101)
```

It is unclear to me if the root cause of this issue is within `glutin_window` or `piston_window`. It may be possible that piston is misusing glutin.

Is there any additional information that I can provide to aid in reproduction of the issue?

**Comment by python50** [comment]
Edit: I found a related issue in the glutin_window repository [https://github.com/PistonDevelopers/glutin_window/issues/187](https://github.com/PistonDevelopers/glutin_window/issues/187)

At the moment, it seems pretty likely that the real problem is with something in `glutin_window` rather than "user error" - but time will tell .

**Comment by bvssvni** [comment]
This should be fixed now with a `cargo update`.
