### ISSUE TITLE
tiled example runtime error

### ISSUE THREAD

**Issue by joshua-barnett** [PistonDevelopers/piston-examples#465]
```
PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> cargo version
cargo 1.48.0 (65cbdd2dc 2020-10-14)

PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)

PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> cmake --version
cmake version 3.19.2

PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> cargo build
   Compiling autocfg v1.0.1
   Compiling cfg-if v0.1.10
   Compiling log v0.4.11
   Compiling khronos_api v3.1.0
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.2.1
   Compiling xml-rs v0.8.3
   Compiling byteorder v1.3.4
   Compiling libc v0.2.81
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.1.0
   Compiling proc-macro2 v1.0.24
   Compiling const_fn v0.4.4
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.2.1
   Compiling winapi v0.3.9
   Compiling piston-float v1.0.0
   Compiling unicode-xid v0.1.0
   Compiling crc32fast v1.2.1
   Compiling syn v1.0.56
   Compiling adler32 v1.2.0
   Compiling rayon-core v1.9.0
   Compiling maybe-uninit v2.0.0
   Compiling serde v1.0.118
   Compiling serde_derive v1.0.118
   Compiling syn v0.15.44
   Compiling piston-graphics_api_version v0.2.0
   Compiling num-derive v0.2.5
   Compiling adler v0.2.3
   Compiling gimli v0.23.0
   Compiling either v1.6.1
   Compiling cc v1.0.66
   Compiling lzw v0.10.0
   Compiling object v0.22.0
   Compiling rustc-demangle v0.1.18
   Compiling color_quant v1.1.0
   Compiling scoped_threadpool v0.1.9
   Compiling piston-texture v0.8.0
   Compiling interpolation v0.2.0
   Compiling read_color v1.0.0
   Compiling fnv v1.0.7
   Compiling take_mut v0.2.2
   Compiling rle-decode-fast v1.0.1
   Compiling piston-shaders_graphics2d v0.3.1
   Compiling bitflags v0.7.0
   Compiling find_folder v0.3.0
   Compiling lock_api v0.3.4
   Compiling semver v0.9.0
   Compiling piston-viewport v1.0.0
   Compiling vecmath v1.0.0
   Compiling num-traits v0.2.14
   Compiling crossbeam-utils v0.8.1
   Compiling memoffset v0.6.1
   Compiling num-integer v0.1.44
   Compiling rayon v1.5.0
   Compiling miniz_oxide v0.4.3
   Compiling num-rational v0.2.4
   Compiling num-iter v0.1.42
   Compiling inflate v0.4.5
   Compiling shader_version v0.6.0
   Compiling gif v0.10.3
   Compiling xml-rs v0.3.6
   Compiling rustc_version v0.2.3
   Compiling draw_state v0.8.0
   Compiling gl_generator v0.14.0
   Compiling gl_generator v0.10.0
   Compiling addr2line v0.14.0
   Compiling num_cpus v1.13.0
   Compiling raw-window-handle v0.3.3
   Compiling libloading v0.5.2
   Compiling stb_truetype v0.3.1
   Compiling deflate v0.7.20
   Compiling base64 v0.5.2
   Compiling quote v1.0.8
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling libflate v0.1.27
   Compiling smallvec v0.6.13
   Compiling quote v0.6.13
   Compiling gfx_core v0.9.2
   Compiling png v0.15.3
   Compiling glutin_egl_sys v0.1.5
   Compiling glutin_wgl_sys v0.1.5
   Compiling gfx_gl v0.6.1
   Compiling gl v0.11.0
   Compiling crossbeam-epoch v0.9.1
   Compiling backtrace v0.3.55
   Compiling tiled v0.8.1
   Compiling approx v0.3.2
   Compiling ordered-float v1.1.1
   Compiling gfx v0.18.2
   Compiling crossbeam-deque v0.8.0
   Compiling winit v0.19.5
   Compiling rusttype v0.8.3
   Compiling rusttype v0.7.9
   Compiling piston2d-graphics v0.35.0
   Compiling glutin v0.21.2
   Compiling gfx_device_gl v0.16.2
   Compiling jpeg-decoder v0.1.20
   Compiling tiff v0.3.1
   Compiling image v0.22.5
   Compiling pistoncore-input v0.28.1
   Compiling pistoncore-window v0.44.0
   Compiling pistoncore-event_loop v0.49.0
   Compiling pistoncore-glutin_window v0.63.0
   Compiling piston v0.49.0
   Compiling piston-gfx_texture v0.40.0
   Compiling piston2d-gfx_graphics v0.66.0
   Compiling piston_window v0.105.0
   Compiling rs-tiled-piston v0.1.0 (C:\Users\Joshua Barnett\projects\piston-examples\tiled)
    Finished dev [unoptimized + debuginfo] target(s) in 42.97s

PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> $env:RUST_BACKTRACE='full'

PS C:\Users\Joshua Barnett\projects\piston-examples\tiled> .\target\debug\rs-tiled-piston.exe
thread 'main' panicked at 'attempted to zero-initialize type `glutin::ContextWrapper<glutin::PossiblyCurrent, glutin::Window>`, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\mem\mod.rs:622:9
stack backtrace:
   0:     0x7ff68ed644e9 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff68ed644e9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff68ed644e9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff68ed644e9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff68ed7afbb - core::fmt::write
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\fmt\mod.rs:1080
   5:     0x7ff68ed60ac8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\io\mod.rs:1516
   6:     0x7ff68ed67274 - std::sys_common::backtrace::_print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff68ed67274 - std::sys_common::backtrace::print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff68ed67274 - std::panicking::default_hook::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:208
   9:     0x7ff68ed66e58 - std::panicking::default_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:227
  10:     0x7ff68ed67b2f - std::panicking::rust_panic_with_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:577
  11:     0x7ff68ed67695 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:484
  12:     0x7ff68ed64dcf - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff68ed67649 - std::panicking::begin_panic_handler
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
  14:     0x7ff68ed78ce0 - core::panicking::panic_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
  15:     0x7ff68ed78c2c - core::panicking::panic
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:50
  16:     0x7ff68e96d337 - core::mem::zeroed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\mem\mod.rs:622
  17:     0x7ff68e96d337 - glutin_window::{{impl}}::make_current
                               at C:\Users\Joshua Barnett\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.63.0\src\lib.rs:511
  18:     0x7ff68e8790c6 - piston_window::PistonWindow<glutin_window::GlutinWindow>::draw_2d<glutin_window::GlutinWindow,input::Event,closure-0,tuple<>>
                               at C:\Users\Joshua Barnett\.cargo\registry\src\github.com-1ecc6299db9ec823\piston_window-0.105.0\src\lib.rs:272
  19:     0x7ff68e87741d - rs_tiled_piston::main
                               at C:\Users\Joshua Barnett\projects\piston-examples\tiled\src\main.rs:42
  20:     0x7ff68e8b264b - core::ops::function::FnOnce::call_once<fn(),tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops\function.rs:227
  21:     0x7ff68e865e4b - std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\sys_common\backtrace.rs:137
  22:     0x7ff68e86ede1 - std::rt::lang_start::{{closure}}<tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\rt.rs:66
  23:     0x7ff68ed67e73 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops\function.rs:280
  24:     0x7ff68ed67e73 - std::panicking::try::do_call
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:381
  25:     0x7ff68ed67e73 - std::panicking::try
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:345
  26:     0x7ff68ed67e73 - std::panic::catch_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panic.rs:382
  27:     0x7ff68ed67e73 - std::rt::lang_start_internal
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\rt.rs:51
  28:     0x7ff68e86edb3 - std::rt::lang_start<tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\rt.rs:65
  29:     0x7ff68e877650 - main
  30:     0x7ff68ed82304 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  31:     0x7ff68ed82304 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  32:     0x7ffaee7b7034 - BaseThreadInitThunk
  33:     0x7ffaefbdd0d1 - RtlUserThreadStart
```

**Comment by VZerda** [comment]
same issue
I just change dependencies in 
piston-examples/examples/tiled/Cargo.toml

modify piston_window = "0.117.0"
and remove "piston" dependency

then it worked
